[gravity]
domain = "default"
host = "localhost"
port = 4222
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1
accessToken = ""

[source]
config = "./settings/sources.json"

[store]
enabled = true
path = "./statestore"
